language: generic

before_install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s $(cat .deno-version)

jobs:
  include:
    - stage: test
      script: "$HOME/.deno/bin/deno test"
    - stage: lint
      script: "$HOME/.deno/bin/deno lint --unstable reno"
    - stage: check formatting
      script: "$HOME/.deno/bin/deno fmt --check reno"

