language: generic

before_install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s v$(cat .deno-version)
  - alias deno="$HOME/.deno/bin/deno"

jobs:
  include:
    - stage: lint
      script: "./scripts/lint.sh"
    - stage: check formatting
      script: "./scripts/format_check.sh"
    - stage: unit tests
      script: "./scripts/test.sh"
    - stage: end-to-end tests
      script: "./scripts/e2e.sh"
