language: generic

before_install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh -s $(cat .deno-version)

jobs:
  include:
    - stage: lint
      script: "$HOME/.deno/bin/deno lint --unstable reno"
    - stage: check formatting
      script: "$HOME/.deno/bin/deno fmt --check reno"
    - stage: unit tests
      script: "$HOME/.deno/bin/deno test"
    - stage: end-to-end tests
      script: "cd e2e-tests && ./ci.sh"

